# Pandas Data Cleaning

In [43]:
import pandas as pd

In [44]:
df = pd.read_csv('data_for_cleaning.csv') # type: ignore

print(df.head())

   Duration        Date  Pulse  Maxpulse  Calories
0        60  2020/12/01    110       130     409.1
1        60  2020/12/02    117       145     479.0
2        60  2020/12/03    103       135     340.0
3        45  2020/12/04    109       175     282.4
4        45  2020/12/05    117       148     406.0

## Data Cleaning

Bad data could be:

1. Empty cells
2. Data in wrong format
3. Wrong data
4. Duplicates

### Empty cells

Empty cells can potentially give you a wrong result when you analyze data.

Methods are:

1. Remove Rows
2. Replace Empty values
3. Replace Using Mean, Median, or Mode

#### Remove Rows

In [45]:
"""This method is usually OK, since data sets can be very big, and removing a few rows will not have a big impact on the result."""

df_1 = df.dropna() # type: ignore

print(df_1.to_string()) # type: ignore

    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020/12/01    110       130     409.1
1         60  2020/12/02    117       145     479.0
2         60  2020/12/03    103       135     340.0
3         45  2020/12/04    109       175     282.4
4         45  2020/12/05    117       148     406.0
5         60  2020/12/06    102       127     300.0
6         60  2020/12/07    110       136     374.0
7        450  2020/12/08    104       134     253.3
8         30  2020/12/09    109       133     195.1
9         60  2020/12/10     98       124     269.0
10        60  2020/12/11    103       147     329.3
11        60  2020/12/12    100       120     250.7
12        60  2020/12/12    100       120     250.7
13        60  2020/12/13    106       128     345.3
14        60  2020/12/14    104       132     379.3
15        60  2020/12/15     98       123     275.0
16        60  2020/12/16     98       120     215.2
17        60  2020/12/17    100       120     300.0
19        60  2020/12/19    103       123     323.0
20        45  2020/12/20     97       125     243.0
21        60  2020/12/21    108       131     364.2
23        60  2020/12/23    130       101     300.0
24        45  2020/12/24    105       132     246.0
25        60  2020/12/25    102       126     334.5
26        60  2020/12/26    100       120     250.0
27        60  2020/12/27     92       118     241.0
29        60  2020/12/29    100       132     280.0
30        60  2020/12/30    102       129     380.3
31        60  2020/12/31     92       115     243.0

#### Replace Empty Values

In [47]:
"""Another way of dealing with empty cells is to insert a new value instead."""

df_2 = df.fillna(0) # type: ignore

print(df_2.to_string()) # type: ignore

    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020/12/01    110       130     409.1
1         60  2020/12/02    117       145     479.0
2         60  2020/12/03    103       135     340.0
3         45  2020/12/04    109       175     282.4
4         45  2020/12/05    117       148     406.0
5         60  2020/12/06    102       127     300.0
6         60  2020/12/07    110       136     374.0
7        450  2020/12/08    104       134     253.3
8         30  2020/12/09    109       133     195.1
9         60  2020/12/10     98       124     269.0
10        60  2020/12/11    103       147     329.3
11        60  2020/12/12    100       120     250.7
12        60  2020/12/12    100       120     250.7
13        60  2020/12/13    106       128     345.3
14        60  2020/12/14    104       132     379.3
15        60  2020/12/15     98       123     275.0
16        60  2020/12/16     98       120     215.2
17        60  2020/12/17    100       120     300.0
18        45  2020/12/18     90       112       0.0
19        60  2020/12/19    103       123     323.0
20        45  2020/12/20     97       125     243.0
21        60  2020/12/21    108       131     364.2
22        45           0    100       119     282.0
23        60  2020/12/23    130       101     300.0
24        45  2020/12/24    105       132     246.0
25        60  2020/12/25    102       126     334.5
26        60  2020/12/26    100       120     250.0
27        60  2020/12/27     92       118     241.0
28        60  2020/12/28    103       132       0.0
29        60  2020/12/29    100       132     280.0
30        60  2020/12/30    102       129     380.3
31        60  2020/12/31     92       115     243.0

In [ ]:
"""Insert value to specific columns"""

df_3 = df.fillna({'Calories': 130}) # type: ignore

print(df_3.to_string()) # type: ignore

    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020/12/01    110       130     409.1
1         60  2020/12/02    117       145     479.0
2         60  2020/12/03    103       135     340.0
3         45  2020/12/04    109       175     282.4
4         45  2020/12/05    117       148     406.0
5         60  2020/12/06    102       127     300.0
6         60  2020/12/07    110       136     374.0
7        450  2020/12/08    104       134     253.3
8         30  2020/12/09    109       133     195.1
9         60  2020/12/10     98       124     269.0
10        60  2020/12/11    103       147     329.3
11        60  2020/12/12    100       120     250.7
12        60  2020/12/12    100       120     250.7
13        60  2020/12/13    106       128     345.3
14        60  2020/12/14    104       132     379.3
15        60  2020/12/15     98       123     275.0
16        60  2020/12/16     98       120     215.2
17        60  2020/12/17    100       120     300.0
18        45  2020/12/18     90       112     130.0
19        60  2020/12/19    103       123     323.0
20        45  2020/12/20     97       125     243.0
21        60  2020/12/21    108       131     364.2
22        45         NaN    100       119     282.0
23        60  2020/12/23    130       101     300.0
24        45  2020/12/24    105       132     246.0
25        60  2020/12/25    102       126     334.5
26        60  2020/12/26    100       120     250.0
27        60  2020/12/27     92       118     241.0
28        60  2020/12/28    103       132     130.0
29        60  2020/12/29    100       132     280.0
30        60  2020/12/30    102       129     380.3
31        60  2020/12/31     92       115     243.0

#### Replace Using Mean, Median, or Mode

In [ ]:
# Mean
"""Calculates the average of all non-missing values in a column and fills NaNs with this average."""

df_4 = df
df_4["Calories"] = df["Calories"].fillna(df["Calories"].mean()) # type: ignore

print(df_4.to_string()) # type: ignore

    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020/12/01    110       130    409.10
1         60  2020/12/02    117       145    479.00
2         60  2020/12/03    103       135    340.00
3         45  2020/12/04    109       175    282.40
4         45  2020/12/05    117       148    406.00
5         60  2020/12/06    102       127    300.00
6         60  2020/12/07    110       136    374.00
7        450  2020/12/08    104       134    253.30
8         30  2020/12/09    109       133    195.10
9         60  2020/12/10     98       124    269.00
10        60  2020/12/11    103       147    329.30
11        60  2020/12/12    100       120    250.70
12        60  2020/12/12    100       120    250.70
13        60  2020/12/13    106       128    345.30
14        60  2020/12/14    104       132    379.30
15        60  2020/12/15     98       123    275.00
16        60  2020/12/16     98       120    215.20
17        60  2020/12/17    100       120    300.00
18        45  2020/12/18     90       112    304.68
19        60  2020/12/19    103       123    323.00
20        45  2020/12/20     97       125    243.00
21        60  2020/12/21    108       131    364.20
22        45         NaN    100       119    282.00
23        60  2020/12/23    130       101    300.00
24        45  2020/12/24    105       132    246.00
25        60  2020/12/25    102       126    334.50
26        60  2020/12/26    100       120    250.00
27        60  2020/12/27     92       118    241.00
28        60  2020/12/28    103       132    304.68
29        60  2020/12/29    100       132    280.00
30        60  2020/12/30    102       129    380.30
31        60  2020/12/31     92       115    243.00

In [ ]:
# Median
"""Replaces NaNs with the middle value of the sorted column."""

df_5 = df
df_5["Duration"] = df["Duration"].fillna(df["Duration"].median()) # type: ignore

print(df_5.to_string()) # type: ignore

    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020/12/01    110       130    409.10
1         60  2020/12/02    117       145    479.00
2         60  2020/12/03    103       135    340.00
3         45  2020/12/04    109       175    282.40
4         45  2020/12/05    117       148    406.00
5         60  2020/12/06    102       127    300.00
6         60  2020/12/07    110       136    374.00
7        450  2020/12/08    104       134    253.30
8         30  2020/12/09    109       133    195.10
9         60  2020/12/10     98       124    269.00
10        60  2020/12/11    103       147    329.30
11        60  2020/12/12    100       120    250.70
12        60  2020/12/12    100       120    250.70
13        60  2020/12/13    106       128    345.30
14        60  2020/12/14    104       132    379.30
15        60  2020/12/15     98       123    275.00
16        60  2020/12/16     98       120    215.20
17        60  2020/12/17    100       120    300.00
18        45  2020/12/18     90       112    304.68
19        60  2020/12/19    103       123    323.00
20        45  2020/12/20     97       125    243.00
21        60  2020/12/21    108       131    364.20
22        45         NaN    100       119    282.00
23        60  2020/12/23    130       101    300.00
24        45  2020/12/24    105       132    246.00
25        60  2020/12/25    102       126    334.50
26        60  2020/12/26    100       120    250.00
27        60  2020/12/27     92       118    241.00
28        60  2020/12/28    103       132    304.68
29        60  2020/12/29    100       132    280.00
30        60  2020/12/30    102       129    380.30
31        60  2020/12/31     92       115    243.00

In [ ]:
# Mode
"""Fills missing values with the most frequent value in the column."""

df_6 = df
df_6["Pulse"] = df['Pulse'].fillna(df['Pulse'].mode()[0]) # type: ignore

print(df_6.to_string()) # type: ignore

    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020/12/01    110       130    409.10
1         60  2020/12/02    117       145    479.00
2         60  2020/12/03    103       135    340.00
3         45  2020/12/04    109       175    282.40
4         45  2020/12/05    117       148    406.00
5         60  2020/12/06    102       127    300.00
6         60  2020/12/07    110       136    374.00
7        450  2020/12/08    104       134    253.30
8         30  2020/12/09    109       133    195.10
9         60  2020/12/10     98       124    269.00
10        60  2020/12/11    103       147    329.30
11        60  2020/12/12    100       120    250.70
12        60  2020/12/12    100       120    250.70
13        60  2020/12/13    106       128    345.30
14        60  2020/12/14    104       132    379.30
15        60  2020/12/15     98       123    275.00
16        60  2020/12/16     98       120    215.20
17        60  2020/12/17    100       120    300.00
18        45  2020/12/18     90       112    304.68
19        60  2020/12/19    103       123    323.00
20        45  2020/12/20     97       125    243.00
21        60  2020/12/21    108       131    364.20
22        45         NaN    100       119    282.00
23        60  2020/12/23    130       101    300.00
24        45  2020/12/24    105       132    246.00
25        60  2020/12/25    102       126    334.50
26        60  2020/12/26    100       120    250.00
27        60  2020/12/27     92       118    241.00
28        60  2020/12/28    103       132    304.68
29        60  2020/12/29    100       132    280.00
30        60  2020/12/30    102       129    380.30
31        60  2020/12/31     92       115    243.00

### Data in Wrong Format

Cells with data of wrong format can make it difficult, or even impossible, to analyze data.

Methods:

1. Convert Into a Correct Format
2. Removing Rows of Specific Column

#### Convert Into a Correct Format

In [62]:
df_7 = df
df_7["Date"] = pd.to_datetime(df["Date"], format="mixed") # type: ignore

print(df_7.to_string()) # type: ignore

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130    409.10
1         60 2020-12-02    117       145    479.00
2         60 2020-12-03    103       135    340.00
3         45 2020-12-04    109       175    282.40
4         45 2020-12-05    117       148    406.00
5         60 2020-12-06    102       127    300.00
6         60 2020-12-07    110       136    374.00
7        450 2020-12-08    104       134    253.30
8         30 2020-12-09    109       133    195.10
9         60 2020-12-10     98       124    269.00
10        60 2020-12-11    103       147    329.30
11        60 2020-12-12    100       120    250.70
12        60 2020-12-12    100       120    250.70
13        60 2020-12-13    106       128    345.30
14        60 2020-12-14    104       132    379.30
15        60 2020-12-15     98       123    275.00
16        60 2020-12-16     98       120    215.20
17        60 2020-12-17    100       120    300.00
18        45 2020-12-18     90       112    304.68
19        60 2020-12-19    103       123    323.00
20        45 2020-12-20     97       125    243.00
21        60 2020-12-21    108       131    364.20
23        60 2020-12-23    130       101    300.00
24        45 2020-12-24    105       132    246.00
25        60 2020-12-25    102       126    334.50
26        60 2020-12-26    100       120    250.00
27        60 2020-12-27     92       118    241.00
28        60 2020-12-28    103       132    304.68
29        60 2020-12-29    100       132    280.00
30        60 2020-12-30    102       129    380.30
31        60 2020-12-31     92       115    243.00

#### Removing Rows of Specific Column

In [64]:
df_8 = df
df_8 = df.dropna(subset=["Date"]) # type: ignore

print(df_8.to_string()) # type: ignore

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130    409.10
1         60 2020-12-02    117       145    479.00
2         60 2020-12-03    103       135    340.00
3         45 2020-12-04    109       175    282.40
4         45 2020-12-05    117       148    406.00
5         60 2020-12-06    102       127    300.00
6         60 2020-12-07    110       136    374.00
7        450 2020-12-08    104       134    253.30
8         30 2020-12-09    109       133    195.10
9         60 2020-12-10     98       124    269.00
10        60 2020-12-11    103       147    329.30
11        60 2020-12-12    100       120    250.70
12        60 2020-12-12    100       120    250.70
13        60 2020-12-13    106       128    345.30
14        60 2020-12-14    104       132    379.30
15        60 2020-12-15     98       123    275.00
16        60 2020-12-16     98       120    215.20
17        60 2020-12-17    100       120    300.00
18        45 2020-12-18     90       112    304.68
19        60 2020-12-19    103       123    323.00
20        45 2020-12-20     97       125    243.00
21        60 2020-12-21    108       131    364.20
23        60 2020-12-23    130       101    300.00
24        45 2020-12-24    105       132    246.00
25        60 2020-12-25    102       126    334.50
26        60 2020-12-26    100       120    250.00
27        60 2020-12-27     92       118    241.00
28        60 2020-12-28    103       132    304.68
29        60 2020-12-29    100       132    280.00
30        60 2020-12-30    102       129    380.30
31        60 2020-12-31     92       115    243.00

### Wrong Data

"Wrong data" does not have to be "empty cells" or "wrong format", it can just be wrong, like if someone registered "199" instead of "1.99".

Methods:
1. Replacing Values
2. Removing Rows

#### Replacing Values

In [ ]:
df.loc[7, 'Duration'] = 45

print(df.to_string()) # type: ignore

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130    409.10
1         60 2020-12-02    117       145    479.00
2         60 2020-12-03    103       135    340.00
3         45 2020-12-04    109       175    282.40
4         45 2020-12-05    117       148    406.00
5         60 2020-12-06    102       127    300.00
6         60 2020-12-07    110       136    374.00
7         45 2020-12-08    104       134    253.30
8         30 2020-12-09    109       133    195.10
9         60 2020-12-10     98       124    269.00
10        60 2020-12-11    103       147    329.30
11        60 2020-12-12    100       120    250.70
12        60 2020-12-12    100       120    250.70
13        60 2020-12-13    106       128    345.30
14        60 2020-12-14    104       132    379.30
15        60 2020-12-15     98       123    275.00
16        60 2020-12-16     98       120    215.20
17        60 2020-12-17    100       120    300.00
18        45 2020-12-18     90       112    304.68
19        60 2020-12-19    103       123    323.00
20        45 2020-12-20     97       125    243.00
21        60 2020-12-21    108       131    364.20
23        60 2020-12-23    130       101    300.00
24        45 2020-12-24    105       132    246.00
25        60 2020-12-25    102       126    334.50
26        60 2020-12-26    100       120    250.00
27        60 2020-12-27     92       118    241.00
28        60 2020-12-28    103       132    304.68
29        60 2020-12-29    100       132    280.00
30        60 2020-12-30    102       129    380.30
31        60 2020-12-31     92       115    243.00

#### Removing Rows

In [ ]:
for x in df.index:
  if df.loc[x, "Duration"] > 120: # type: ignore
    df.drop(x, inplace = True)

print(df.to_string()) # type: ignore

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130    409.10
1         60 2020-12-02    117       145    479.00
2         60 2020-12-03    103       135    340.00
3         45 2020-12-04    109       175    282.40
4         45 2020-12-05    117       148    406.00
5         60 2020-12-06    102       127    300.00
6         60 2020-12-07    110       136    374.00
7         45 2020-12-08    104       134    253.30
8         30 2020-12-09    109       133    195.10
9         60 2020-12-10     98       124    269.00
10        60 2020-12-11    103       147    329.30
11        60 2020-12-12    100       120    250.70
12        60 2020-12-12    100       120    250.70
13        60 2020-12-13    106       128    345.30
14        60 2020-12-14    104       132    379.30
15        60 2020-12-15     98       123    275.00
16        60 2020-12-16     98       120    215.20
17        60 2020-12-17    100       120    300.00
18        45 2020-12-18     90       112    304.68
19        60 2020-12-19    103       123    323.00
20        45 2020-12-20     97       125    243.00
21        60 2020-12-21    108       131    364.20
23        60 2020-12-23    130       101    300.00
24        45 2020-12-24    105       132    246.00
25        60 2020-12-25    102       126    334.50
26        60 2020-12-26    100       120    250.00
27        60 2020-12-27     92       118    241.00
28        60 2020-12-28    103       132    304.68
29        60 2020-12-29    100       132    280.00
30        60 2020-12-30    102       129    380.30
31        60 2020-12-31     92       115    243.00

### Duplicates

In [ ]:
print(df.duplicated()) # type: ignore

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12     True
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
dtype: bool

In [ ]:
df.drop_duplicates(inplace = True)
print(df.to_string()) # type: ignore

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130    409.10
1         60 2020-12-02    117       145    479.00
2         60 2020-12-03    103       135    340.00
3         45 2020-12-04    109       175    282.40
4         45 2020-12-05    117       148    406.00
5         60 2020-12-06    102       127    300.00
6         60 2020-12-07    110       136    374.00
7         45 2020-12-08    104       134    253.30
8         30 2020-12-09    109       133    195.10
9         60 2020-12-10     98       124    269.00
10        60 2020-12-11    103       147    329.30
11        60 2020-12-12    100       120    250.70
13        60 2020-12-13    106       128    345.30
14        60 2020-12-14    104       132    379.30
15        60 2020-12-15     98       123    275.00
16        60 2020-12-16     98       120    215.20
17        60 2020-12-17    100       120    300.00
18        45 2020-12-18     90       112    304.68
19        60 2020-12-19    103       123    323.00
20        45 2020-12-20     97       125    243.00
21        60 2020-12-21    108       131    364.20
23        60 2020-12-23    130       101    300.00
24        45 2020-12-24    105       132    246.00
25        60 2020-12-25    102       126    334.50
26        60 2020-12-26    100       120    250.00
27        60 2020-12-27     92       118    241.00
28        60 2020-12-28    103       132    304.68
29        60 2020-12-29    100       132    280.00
30        60 2020-12-30    102       129    380.30
31        60 2020-12-31     92       115    243.00